/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param summary 
 */


data class RequestModelB (

    @SerializedName("type")
    val type: RequestModelB.Type,

    @SerializedName("summary")
    val summary: kotlin.String

) {

    /**
     * 
     *
     * Values: VALUE1,VALUE2,VALUE3
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "value1") VALUE1("value1"),
        @SerializedName(value = "value2") VALUE2("value2"),
        @SerializedName(value = "value3") VALUE3("value3");
    }
}

