/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param expires 
 * @param value1 
 * @param value2 
 * @param valueType 
 */


data class ResponseModelA (

    @SerializedName("expires")
    val expires: kotlin.Int,

    @SerializedName("value_1")
    val value1: kotlin.String,

    @SerializedName("value_2")
    val value2: kotlin.String,

    @SerializedName("value_type")
    val valueType: kotlin.String? = null

)

