/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RequestModelA
import org.openapitools.client.models.RequestModelB
import org.openapitools.client.models.RequestModelC

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param type 
 * @param scope 
 * @param name 
 * @param description 
 * @param summary 
 * @param key 
 */


data class V1EndpointPostRequest (

    @SerializedName("id")
    val id: kotlin.String,

    @SerializedName("type")
    val type: V1EndpointPostRequest.Type,

    @SerializedName("scope")
    val scope: kotlin.String,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("description")
    val description: kotlin.String,

    @SerializedName("summary")
    val summary: kotlin.String,

    @SerializedName("key")
    val key: kotlin.String

) {

    /**
     * 
     *
     * Values: VALUE1,VALUE2,VALUE3
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "value1") VALUE1("value1"),
        @SerializedName(value = "value2") VALUE2("value2"),
        @SerializedName(value = "value3") VALUE3("value3");
    }
}

